---

app_name: example_app
repo_url: https://github.com/example_hacker/example_app.git
bundle_path: false
domain_name: www.example.org

#########################################################

repo_version: master
root_url: "http://{{ domain_name }}"
cordova_host: "{{ domain_name }}:80"
deploy_dir: /var/www
deploy_app_dir: "/var/www/{{ app_name }}"
mongo_url: "mongodb://localhost:27017/{{ app_name}}"
repo_remote: true
port: 8003
nginx_upstream_name: "{{ app_name }}"
nginx_upstream_server: "127.0.0.1:{{ port }}"

nginx_server_listen: 0.0.0.0:80
nginx_server_log: /var/log/nginx/meteor.log
nginx_server_root: "{{ deploy_app_dir}}"
nginx_server_index: index.html index.htm
nginx_server_proxy_pass: "http://{{ app_name }}/"

pid_expression: "/var/www/{{ app_name }}/build/bundle/main.js"
